# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to register a userid / username mapping

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"

Resources:
    RegisterUserMappingFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: register-user-mapping.default
            # Runtime: nodejs8.10
            Runtime: nodejs10.x
            Timeout: 3
            MemorySize: 128
            ReservedConcurrentExecutions: 40
            CodeUri: ./dist/register-user-mapping
            # https://stackoverflow.com/questions/39144688/aws-lambda-invoke-not-calling-another-lambda-function-node-js
            VpcConfig:
                SecurityGroupIds:
                    - sg-0ed63616362bf1a30
                SubnetIds:
                    - subnet-0b730ca9af74a95dd
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-register-user-mapping
            Events:
                RegisterUserMappingResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    RegisterUserMappingApi:
        Description: URL to register a userId / userName mapping
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/userMapping'
        Export:
            Name: RegisterUserMappingApi
